### ISSUE TITLE
templates

### ISSUE THREAD

**Issue by joej** [idlesign/django-admirarchy#3]
pip install django-admirarchy

I altered APP/admin.py to match the instructions
Issues:
1... parent issue, so I altered to match, assuming the example suggested that I use the ForeignKey field name in the AdjacencyList() argument. I guess this works.
2... no templates to serve, so cannot use admin (/admin/APP/model) to see if this even works

So, I searched & found admirarchy templates in /usr/local/lib/python2.7/site-packages/etc.
I copied them down into the local /static/admin directory (cp -r) and the existing admirarchy template structure doesn't match any directory structure for the change_list.html expectations (in utils.py)

So, I altered (mv/mkdir/etc) the admin and registration into some structure that made the 500 error code go away.

Question:
- no docs on how to use this beyond the simple admin.py (hierarchichalmodeladmin) explanation?
- what is the correct template structure? what is registration sub-dir for?

**Comment by idlesign** [comment]
> no docs on how to use this beyond the simple admin.py (hierarchichalmodeladmin) explanation?

That's because none required. After admin.py is configured you'd be able to navigate your hierachical data.

> what is the correct template structure? what is registration sub-dir for?

Normally you do not need to do anything with templates, as it's handled by Django's Static Files contrib.

It seems that issue is somehow related to Static Files. What Django version do you have?

**Comment by idlesign** [comment]
Closing this one as inactive.
