### ISSUE TITLE
Django 2 compability

### ISSUE THREAD

**Issue by rbreu** [idlesign/django-admirarchy#5]
We've just upgraded our code to the latest Django 2.x release and django-admirarchy stopped working with the following error message:

```
File "some/path/lib/python3.6/site-packages/django/contrib/admin/options.py", line 742, in get_changelist_instance
    sortable_by,
  File "/some/path/lib/python3.6/site-packages/admirarchy/utils.py", line 92, in __init__
    model_admin._current_changelist = self
AttributeError: 'tuple' object has no attribute '_current_changelist'
```
The reason is that the __init__ method of ChangeList got another argument, throwing off the way HierarchicalChangeList expects the arguments.

Here's a simple fix, though this will work **only** for Django 2:

https://github.com/rbreu/django-admirarchy/commit/bf8d001ca8f8aa1f0f326b2c8990ee754e45aa0d

Not sure how you prefer to handle compability with both major Django versions in this case, or else I'd submit a pull request. ;)

**Comment by idlesign** [comment]
Thank you for the report.
I'd like to make it 1.7+ compatible.

You're welcome to make a pull request.
