### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by rmarchenko** [idlesign/django-admirarchy#7]
I got UnicodeEncodeError in admirarchy/utils.py in hierarchy_nav line 88.
Python 2.7
If i remove 'title' attr from this line or 'ru' locale files - it's work fine.

**Comment by idlesign** [comment]
Thank you for the report.
I'll try to check it in a couple of days.

**Comment by idlesign** [comment]
Seems to be fixed in 0.2.4. Please, give it a try.
Considered closed. Feel free to reopen if required.
